# Generated by Django 5.2.1 on 2025-06-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('confidence', models.FloatField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detector.uploadedimage')),
            ],
        ),
    ]
